version: '3.8'
services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: my_user
            POSTGRES_PASSWORD: my_password
            POSTGRES_DB: book_db
        ports:
            - '5432:5433'
        volumes:
            - postgres-data:/var/lib/postgresql/data

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
            - ./backend/.env
        ports:
            - '8000:8000'
        depends_on:
            - db
    migrate:
        build:
            context: ./backend
            dockerfile: Dockerfile
        depends_on:
            - backend
        command: alembic upgrade head

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - backend
volumes:
    postgres-data:
