"""change status to status_id

Revision ID: e120ea94b4f3
Revises: 8c0208e6c975
Create Date: 2023-08-19 22:20:18.169824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e120ea94b4f3'
down_revision: Union[str, None] = '8c0208e6c975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'status', ['status_id'], ['id'])
    op.create_index(op.f('ix_status_id'), 'status', ['id'], unique=False)

    op.execute("INSERT INTO status (name) VALUES ('To Read')")
    op.execute("INSERT INTO status (name) VALUES ('In Progress')")
    op.execute("INSERT INTO status (name) VALUES ('COmpleted')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_id'), table_name='status')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'status_id')
    # ### end Alembic commands ###
